### ISSUE TITLE
Error during build: check-geojson.esm.js

### ISSUE THREAD

**Issue by moranbw** [placemark/check-geojson#23]
Hi there, I receive the following error while running a build with [Vite](https://vitejs.dev/):

```
[vite:resolve] Failed to resolve entry for package "@placemarkio/check-geojson". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "@placemarkio/check-geojson". The package may have incorrect main/module/exports specified in its package.json.
error during build:
Error: Failed to resolve entry for package "@placemarkio/check-geojson". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "@placemarkio/check-geojson". The package may have incorrect main/module/exports specified in its package.json.
    at packageEntryFailure (/home/brian/Dev/parent-aoi-tasks/frontend/node_modules/vite/dist/node/chunks/dep-611778e0.js:38290:11)
    at resolvePackageEntry (/home/brian/Dev/parent-aoi-tasks/frontend/node_modules/vite/dist/node/chunks/dep-611778e0.js:38286:9)
    at tryNodeResolve (/home/brian/Dev/parent-aoi-tasks/frontend/node_modules/vite/dist/node/chunks/dep-611778e0.js:38093:20)
    at Object.resolveId (/home/brian/Dev/parent-aoi-tasks/frontend/node_modules/vite/dist/node/chunks/dep-611778e0.js:37901:28)
    at /home/brian/Dev/parent-aoi-tasks/frontend/node_modules/rollup/dist/shared/rollup.js:22779:37
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

I believe the issue is that in your `package.json`, you have `"module": "dist/check-geojson.esm.js"`.  `check-geojson.esm.js` doesn't seem to exist?  The build completes when I remove this line.  I'm wondering if this now should reference `index.esm.js`?

**Comment by tmcw** [comment]
Indeed, yep - thanks! Fixed in 0.1.10
